Bump gitleaks from 8.19.3 to 8.22.0

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -9,13 +9,15 @@ inputs:
   version:
     description: "Umka version."
     required: false
-    default: "1.5"
+    default: "1.5.1"
 runs:
   using: "composite"
   steps:
     - name: Fail
       if: ${{ runner.os == 'macOS' }}
-      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
+      run: |
+        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
+        exit 1
       shell: sh
     - name: Collect info
       if: ${{ runner.os != 'macOS' }}
@@ -33,11 +35,7 @@ runs:
         echo "umka-installed=$(if command -v "${exec_name}" >/dev/null 2>&1; then echo true; else echo false; fi)" >> "$GITHUB_OUTPUT"
         mkdir -p "${GITHUB_WORKSPACE}/umka"
         echo "umka-path=${GITHUB_WORKSPACE}/umka" >> "$GITHUB_OUTPUT"
-        file_name="umka_${INPUT_VERSION}"
-        if [ "${INPUT_VERSION}" != "1.3" ] && [ "${INPUT_VERSION}" != "1.3.1" ] && [ "${INPUT_VERSION}" != "1.4" ] && [ "${INPUT_VERSION}" != "1.4.1" ] && [ "${INPUT_VERSION}" != "1.5" ]; then
-          file_name="${file_name}_x86-64"
-        fi
-        file_name="${file_name}_${bin_name}"
+        file_name="umka_${INPUT_VERSION}_${bin_name}"
         echo "file-name=${file_name}" >> "$GITHUB_OUTPUT"
       shell: sh
     - name: Download umka
