Add "Security" workflow

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -14,25 +14,24 @@ runs:
   using: "composite"
   steps:
     - name: Fail
-      uses: actions/github-script@v7
       if: ${{ runner.os == 'macOS' }}
-      with:
-        script: core.setFailed('${{ runner.os }} ${{ runner.arch }} is not supported');
+      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
+      shell: sh
     - name: Collect info
       if: ${{ runner.os != 'macOS' }}
       id: info
       run: |
-        if [ "${{ runner.os }}" = "Linux" ]; then
+        if [ "${RUNNER_OS}" = "Linux" ]; then
           UMKA_BINARY=linux
           UMKA_EXEC=umka
         else
           UMKA_BINARY=windows_mingw
           UMKA_EXEC=umka.exe
         fi
-        echo "UMKA_BINARY=$UMKA_BINARY" >> $GITHUB_OUTPUT
-        echo "UMKA_INSTALLED=$(if command -v $UMKA_EXEC >/dev/null 2>&1; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
-        mkdir -p "$GITHUB_WORKSPACE/umka"
-        echo "UMKA_PATH=$GITHUB_WORKSPACE/umka" >> $GITHUB_OUTPUT
+        echo "UMKA_BINARY=${UMKA_BINARY}" >> $GITHUB_OUTPUT
+        echo "UMKA_INSTALLED=$(if command -v "${UMKA_EXEC}" >/dev/null 2>&1; then echo true; else echo false; fi)" >> "$GITHUB_OUTPUT"
+        mkdir -p "${GITHUB_WORKSPACE}/umka"
+        echo "UMKA_PATH=${GITHUB_WORKSPACE}/umka" >> $GITHUB_OUTPUT
       shell: sh
     - name: Download umka
       if: ${{ steps.info.outputs.UMKA_INSTALLED == 'false' }}
@@ -47,12 +46,14 @@ runs:
         out-file-path: umka
     - name: Install umka
       if: ${{ steps.info.outputs.UMKA_INSTALLED == 'false' }}
+      env:
+        INPUT_VERSION: "${{ inputs.version }}"
       run: |
-        unzip umka_${{ inputs.version }}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}.zip
-        rm -f umka_${{ inputs.version }}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}.zip
-        if [ "${{ runner.os }}" != "Windows" ]; then
-          chmod +x "${{ steps.info.outputs.UMKA_PATH }}/umka_${{ inputs.version }}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}/umka"
+        unzip "umka_${INPUT_VERSION}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}.zip"
+        rm -f "umka_${INPUT_VERSION}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}.zip"
+        if [ "${RUNNER_OS}" != "Windows" ]; then
+          chmod +x "${{ steps.info.outputs.UMKA_PATH }}/umka_${INPUT_VERSION}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}/umka"
         fi
-        echo "${{ steps.info.outputs.UMKA_PATH }}/umka_${{ inputs.version }}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}" >> $GITHUB_PATH
+        echo "${{ steps.info.outputs.UMKA_PATH }}/umka_${INPUT_VERSION}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}" >> "$GITHUB_PATH"
       shell: sh
       working-directory: ${{ steps.info.outputs.UMKA_PATH }}
