Test 8

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -45,10 +45,30 @@ jobs:
     steps:
       - name: Checkout ${{ github.repository }}
         uses: actions/checkout@v4
-      - name: Setup Umka
+      - name: Setup Umka 1
+        id: setup-umka-1
         uses: ./
         with:
           version: ${{ matrix.version }}
+      - name: Setup Umka 2
+        id: setup-umka-2
+        uses: ./
+        with:
+          version: ${{ matrix.version }}
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "First action had to install umka" \
+            "${{ steps.setup-umka-1.outputs.installed }}" \
+            "true"
+          test_equal "Second action should not install umka" \
+            "${{ steps.setup-umka-2.outputs.installed }}" \
+            "false"
       - name: Run script
         run: umka ./hello-world.um
   macos-not-supported:
@@ -62,6 +82,17 @@ jobs:
         id: setup-umka
         continue-on-error: true
         uses: ./
-      - name: Validate outcome
-        if: ${{ steps.setup-umka.outcome != 'failure' }}
-        run: exit 1
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong completion status" \
+            "${{ steps.setup-umka.outcome }}" \
+            "failure"
+          test_equal "umka should not be installed" \
+            "${{ steps.setup-umka.outputs.installed }}" \
+            "false"
